### ISSUE TITLE
Help for the dataset

### ISSUE THREAD

**Issue by hityzy1122** [NVIDIA/unsupervised-video-interpolation#1]
Thanks for the release of the code. However I can find the dataset of Slowflow-240fps and Sintel-1008fps on this website http://www.cvlibs.net/projects/slow_flow/. As the provided "Benchmark Dataset" and "Teaser Dataset" don't seem to be the  Slowflow-240fps or Sintel-1008fps in this website.

looking forward to your replay
Thanks

**Comment by fitsumreda** [comment]
Hi, Just saw the issue now. Will look into it and get back to you.

**Comment by hityzy1122** [comment]
> Hi, Just saw the issue now. Will look into it and get back to you.

Thanks!!!!
