### ISSUE TITLE
The performance in UCF101 is bad..

### ISSUE THREAD

**Issue by pongkun** [NVIDIA/unsupervised-video-interpolation#8]
I use this code to eval the pre-train model on UCF101, but the PSNR and SSIM are lower than the values in the paper.

python3 eval.py --model CycleHJSuperSloMo --num_interp 1 --flow_scale 1 --dataset CycleVideoInterp --val_batch_size 1 --val_file /home/data/VFI/ucf101_interp_for_paper --name Pretrain_FullUnsupervised_Adobe_ucf101_3.31 --save /home/wpk/VFI/code/result_folder --post_fix wpk --resume /home/wpk/VFI/code/pretrained_models/fully_unsupervised_adobe30fps.pth --val_sample_rate 1 --val_step_size 1 --write_images

PSNR and SSIM in the paper are 34.47 and 0.946
and i get,
![image](https://user-images.githubusercontent.com/21241974/113109883-00d9d880-9239-11eb-9294-e2c24e4595b8.png)

**Comment by fitsumreda** [comment]
Can you just try this as exactly shown here?
```
python3 eval.py --model CycleHJSuperSloMo --num_interp 1 --flow_scale 1 --val_file /path/to/ucf/root \
    --resume ./pretrained_models/fully_unsupervised_adobe30fps.pth
 ```

**Comment by pongkun** [comment]
oh, this is my mistake, I get bad results because I ignore these warnings, and now I get the right PSNR and SSIM, thanks.
![image](https://user-images.githubusercontent.com/21241974/113235838-6039f600-92d6-11eb-97c4-df730b587590.png)
